# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 17000 ]
  pull_request:
    branches: [ master ]

env:
  ROM_URL: http://bigota.d.miui.com/20.4.27/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip
  mipay_extract_repo: https://github.com/linusyang92/mipay-extract
  mipay_extract_branch: master
  magisk_module_repo: https://github.com/biner/magisk-module-template
  magisk_module_branch: 17000

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

        

        

    # 下载文件
    - name: 【Cache】 ROM
      id: cache-primes
      uses: actions/cache@master
      env:
        cache-name: mi9
      with:
        path: ./rom
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Download
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install axel
        mkdir ./rom
        cd ./rom
        axel -a -n 10 $ROM_URL
        #wget http://bigota.d.miui.com/20.4.27/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip
   
        
               
    # mipay
    - name: 【mipay】 Clone source code
      run: |
        git clone --depth 1 $mipay_extract_repo -b $mipay_extract_branch mipay-extract
        cd mipay-extract
        cp ../rom/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip ./
        chmod +x extract.sh
        ./extract.sh --appvault
        mkdir ./targets
        cp mipay*.zip ./targets
        cp eufix*.zip ./targets
        ls -lna


        
    - name: 【Custom】 Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Mipay
        path: ./mipay-extract/targets/
        
        
    # mipay
    - name: 【mipay】 Clone source code
      run: |
        
        git clone --depth 1 $magisk_module_repo -b $magisk_module_branch magisk
        cd ./mipay-extract
        ls -lna
        unzip mipay-CEPHEUS-20.4.27.zip
        cd mipay-CEPHEUS-20.4.27
        ls -lna
        cd ..
        
        cp ./mipay-extract/mipay-CEPHEUS-20.4.27/system/app ./magisk/system/app
        cd ./magisk/system/app
        ls -lna


    - name: 【Custom】 Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: magisk
        path: ./magisk/
