# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  rom-url: http://bigota.d.miui.com/20.4.27/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip
  mipay-extract-repo: https://github.com/linusyang92/mipay-extract
  mipay-extract-branch: master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

        

        

    # 下载文件
    - name: 【Cache】 ROM
      id: cache-primes
      uses: actions/cache@master
      env:
        cache-name: mi9
      with:
        path: ./rom
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install axel
        mkdir ./rom
        cd ./rom
        axel -a -n 10 $rom_url
        #wget http://bigota.d.miui.com/20.4.27/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip
        
    # mipay
    - name: 【mipay】 Clone source code
      run: |
        git clone --depth 1 $mipay-extract-repo -b $mipay-extract-branch mipay-extract
        cd mipay-extract
        cp ../rom/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip ./
        chmod +x extract.sh
        ./extract.sh --appvault
        ls -lna
        mkdir ./targets
        cp mipay*.zip ./targets
        cp eufix*.zip ./targets

        
    - name: 【Custom】 Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Mipay
        path: ./targets/
        

        
        
          
